if ( 'prettyPrint' in window ) {} else {
    document.write( '<script type="text/javascript" src="http://gist-it.appspot.com/assets/prettify/prettify.js"></script>' );
}


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/embed.css"/>' );


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/prettify/prettify.css"/>' );

document.write( '<div class="gist-it-gist">\n<div class="gist-file">\n    <div class="gist-data">\n        \n        <pre class="prettyprint">class Foo\n  EQ = {\n    3 =&gt; "Foo",\n    5 =&gt; "Bar",\n    7 =&gt; "Qix"\n  }\n\n  def self.eval(i)\n    retour = divisible_ou_contient_un_chiffre(i)\n    retour != "" ? retour : i.to_s\n  end\n\n  def self.divisible_ou_contient_un_chiffre(i)\n    listes_des_diviseurs(i).join("") \\\n    + lettres(i).map { |lettre| symbol_equivalent(lettre) }.join("")\n  end\n\n  def self.listes_des_diviseurs(i)\n    EQ.select { |k| i % k == 0 }.values\n  end\n\n  def self.lettres(i)\n    i.to_s.split("")\n  end\n\n  def self.symbol_equivalent(lettre)\n    EQ[lettre.to_i]\n  end\nend</pre>\n        \n    </div>\n    \n    <div class="gist-meta">\n        \n        <span><a href="https://github.com/guillaumerose/FooBarQix/blob/master/ruby/lib/foo.rb">This Gist</a> brought to you by <a href="http://gist-it.appspot.com">gist-it</a>.</span>\n        \n        <span style="float: right; color: #369;"><a href="https://github.com/guillaumerose/FooBarQix/raw/master/ruby/lib/foo.rb">view raw</a></span>\n        <span style="float: right; margin-right: 8px;">\n            <a style="color: rgb(102, 102, 102);" href="https://github.com/guillaumerose/FooBarQix/blob/master/ruby/lib/foo.rb">foo.rb</a></span>\n            <!-- Generated by: http://gist-it.appspot.com -->\n    </div>\n    \n</div>\n</div>' );

document.write( '<script type="text/javascript">prettyPrint();</script>' );