if ( 'prettyPrint' in window ) {} else {
    document.write( '<script type="text/javascript" src="http://gist-it.appspot.com/assets/prettify/prettify.js"></script>' );
}


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/embed.css"/>' );


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/prettify/prettify.css"/>' );

document.write( '<div class="gist-it-gist">\n<div class="gist-file">\n    <div class="gist-data">\n        \n        <pre class="prettyprint">class ChallengeHelper {\n    static m = [3:\'Foo\', 5:\'Bar\', 7:\'Qix\'] as TreeMap\n\n    static divideTransform (Integer self){\n        m.collect { k, v -&gt;\n            m[k] &amp;&amp; self % k == 0 ? v : \'\' \n        }.join()\n    }\n    static containsTransform (Integer self){\n        (self as String).collect { s -&gt;\n            m[s as int] ?: \'\'\n        }.join()\n    }\n\n}\n\nuse (ChallengeHelper){\n    (1..100).each {i -&gt; \n        println i.divideTransform() + i.containsTransform() ?: i\n    }\n}\n</pre>\n        \n    </div>\n    \n    <div class="gist-meta">\n        \n        <span><a href="https://github.com/boillodmanuel/codestory/blob/master/src/foobarqix.groovy">This Gist</a> brought to you by <a href="http://gist-it.appspot.com">gist-it</a>.</span>\n        \n        <span style="float: right; color: #369;"><a href="https://github.com/boillodmanuel/codestory/raw/master/src/foobarqix.groovy">view raw</a></span>\n        <span style="float: right; margin-right: 8px;">\n            <a style="color: rgb(102, 102, 102);" href="https://github.com/boillodmanuel/codestory/blob/master/src/foobarqix.groovy">foobarqix.groovy</a></span>\n            <!-- Generated by: http://gist-it.appspot.com -->\n    </div>\n    \n</div>\n</div>' );

document.write( '<script type="text/javascript">prettyPrint();</script>' );