if ( 'prettyPrint' in window ) {} else {
    document.write( '<script type="text/javascript" src="http://gist-it.appspot.com/assets/prettify/prettify.js"></script>' );
}


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/embed.css"/>' );


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/prettify/prettify.css"/>' );

document.write( '<div class="gist-it-gist">\n<div class="gist-file">\n    <div class="gist-data">\n        \n        <pre class="prettyprint">package fcx.codestory\n\nobject FooBarQix1 extends App {\n  for (i &lt;- 1 to 100) \n    Console.println((i.toString() * ((1 / (1 + ("Foo" * (1 / (1 + (i % 3)))) + ("Bar" * (1 / (1 + (i % 5)))) + ("Qix" * (1 / (1 + (i % 7)))) + ("Foo" * (1 / (1 + ((i / 10 - 3).abs % 10)))) + ("Foo" * (1 / (1 + ((i - 3).abs % 10)))) + ("Bar" * (1 / (1 + ((i / 10 - 5).abs % 10)))) + ("Bar" * (1 / (1 + ((i - 5).abs % 10)))) + ("Qix" * (1 / (1 + ((i / 10 - 7).abs % 10)))) + ("Qix" * (1 / (1 + ((i - 7).abs % 10))))).size))) + ("Foo" * (1 / (1 + (i % 3)))) + ("Bar" * (1 / (1 + (i % 5)))) + ("Qix" * (1 / (1 + (i % 7)))) + ("Foo" * (1 / (1 + ((i / 10 - 3).abs % 10)))) + ("Bar" * (1 / (1 + ((i / 10 - 5).abs % 10)))) + ("Qix" * (1 / (1 + ((i / 10 - 7).abs % 10)))) + ("Foo" * (1 / (1 + ((i - 3).abs % 10)))) + ("Bar" * (1 / (1 + ((i - 5).abs % 10)))) + ("Qix" * (1 / (1 + ((i - 7).abs % 10)))))\n  }\n</pre>\n        \n    </div>\n    \n    <div class="gist-meta">\n        \n        <span><a href="https://github.com/fcroiseaux/FooBarQix-scala/blob/master/src/main/scala/fcx/codestory/FooBarQix1.scala">This Gist</a> brought to you by <a href="http://gist-it.appspot.com">gist-it</a>.</span>\n        \n        <span style="float: right; color: #369;"><a href="https://github.com/fcroiseaux/FooBarQix-scala/raw/master/src/main/scala/fcx/codestory/FooBarQix1.scala">view raw</a></span>\n        <span style="float: right; margin-right: 8px;">\n            <a style="color: rgb(102, 102, 102);" href="https://github.com/fcroiseaux/FooBarQix-scala/blob/master/src/main/scala/fcx/codestory/FooBarQix1.scala">FooBarQix1.scala</a></span>\n            <!-- Generated by: http://gist-it.appspot.com -->\n    </div>\n    \n</div>\n</div>' );

document.write( '<script type="text/javascript">prettyPrint();</script>' );