if ( 'prettyPrint' in window ) {} else {
    document.write( '<script type="text/javascript" src="http://gist-it.appspot.com/assets/prettify/prettify.js"></script>' );
}


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/embed.css"/>' );


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/prettify/prettify.css"/>' );

document.write( '<div class="gist-it-gist">\n<div class="gist-file">\n    <div class="gist-data">\n        \n        <pre class="prettyprint">function getFooBarQix(total) {\n    var result = [];\n    var values = {\n        3: "Foo",\n        5: "Bar",\n        7: "Qix"\n    };\n    for (var i = 1; i &lt;= total; i++) {\n        var numberRepresentation = "";\n        var found = false;\n        for (var num in values) {\n            if (i % num === 0) {\n                numberRepresentation += values[num];\n                found = true;\n            }\n        }\n        var iAsString = String(i);\n        for (var j = 0; j &lt; iAsString.length; j++) {\n            var digit = Number(iAsString.charAt(j));\n            var value = values[digit];\n            if (typeof (value) !== "undefined") {\n                numberRepresentation += value;\n                found = true;\n            }\n        }\n        if (!found) {\n            numberRepresentation += i;\n        }\n        result.push(numberRepresentation);\n    }\n    return result;\n}\n</pre>\n        \n    </div>\n    \n    <div class="gist-meta">\n        \n        <span><a href="https://github.com/a14n/FooBarQix/blob/master/js/fooBarQix.js">This Gist</a> brought to you by <a href="http://gist-it.appspot.com">gist-it</a>.</span>\n        \n        <span style="float: right; color: #369;"><a href="https://github.com/a14n/FooBarQix/raw/master/js/fooBarQix.js">view raw</a></span>\n        <span style="float: right; margin-right: 8px;">\n            <a style="color: rgb(102, 102, 102);" href="https://github.com/a14n/FooBarQix/blob/master/js/fooBarQix.js">fooBarQix.js</a></span>\n            <!-- Generated by: http://gist-it.appspot.com -->\n    </div>\n    \n</div>\n</div>' );

document.write( '<script type="text/javascript">prettyPrint();</script>' );