if ( 'prettyPrint' in window ) {} else {
    document.write( '<script type="text/javascript" src="http://gist-it.appspot.com/assets/prettify/prettify.js"></script>' );
}


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/embed.css"/>' );


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/prettify/prettify.css"/>' );

document.write( '<div class="gist-it-gist">\n<div class="gist-file">\n    <div class="gist-data">\n        \n        <pre class="prettyprint">package fcx.codestory\n\nobject FooBarQix2 extends App {\n\n  foobarqix(100)\n\n  def rpl = List("", "", "", "Foo", "", "Bar", "", "Qix", "", "", "")\n  /*\n  * norm retourne la chaine s si i est egal a 0, retourne une chaine vide sinon\n  */\n  def norm(s: String, i: Int): String = s * (1 / (1 + i.abs))\n\n  def convert(i: Int): String = {\n    var s = ""\n    for (nb &lt;- 1 to 9)\n      s += norm(rpl(nb), i % nb) // i est divible par n\n    for (exp &lt;- math.log10(i).toInt to 0 by -1)\n      for (nb &lt;- 1 to 9)\n        s += norm(rpl(nb), ((i / ((math.pow(10, exp)).toInt)) - nb) % 10) // i contient nb en exp &#232;me position\n    norm(i.toString(), s.size) + s // si s.size = 0 on retourne i, s sinon\n  }\n\n  def foobarqix(max: Int) {\n    for (i &lt;- 1 to max)\n      Console.println(convert(i))\n  }\n\n}\n</pre>\n        \n    </div>\n    \n    <div class="gist-meta">\n        \n        <span><a href="https://github.com/fcroiseaux/FooBarQix-scala/blob/master/src/main/scala/fcx/codestory/FooBarQix2.scala">This Gist</a> brought to you by <a href="http://gist-it.appspot.com">gist-it</a>.</span>\n        \n        <span style="float: right; color: #369;"><a href="https://github.com/fcroiseaux/FooBarQix-scala/raw/master/src/main/scala/fcx/codestory/FooBarQix2.scala">view raw</a></span>\n        <span style="float: right; margin-right: 8px;">\n            <a style="color: rgb(102, 102, 102);" href="https://github.com/fcroiseaux/FooBarQix-scala/blob/master/src/main/scala/fcx/codestory/FooBarQix2.scala">FooBarQix2.scala</a></span>\n            <!-- Generated by: http://gist-it.appspot.com -->\n    </div>\n    \n</div>\n</div>' );

document.write( '<script type="text/javascript">prettyPrint();</script>' );