if ( 'prettyPrint' in window ) {} else {
    document.write( '<script type="text/javascript" src="http://gist-it.appspot.com/assets/prettify/prettify.js"></script>' );
}


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/embed.css"/>' );


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/prettify/prettify.css"/>' );

document.write( '<div class="gist-it-gist">\n<div class="gist-file">\n    <div class="gist-data">\n        \n        <pre class="prettyprint">\nclass FooBarQix\n{\n  static Void main(Str[] args)  {\n    fooBarQix := FooBarQix {}\n    (1..100).each |Int c| { echo(fooBarQix.asText(c)) }\n  }\n\n  const Map digitsToStrings := [3:"Foo", 5:"Bar", 7:"Qix"]\n  Str asText(Int value)\n  {\n    result := asTextFromMultiple(value) + asTextFromDigit(value)\n    return result == "" ? "" + value : result\n  }\n  \n  private Str asTextFromMultiple(Int number)\n  {\n    return digitsToStrings.keys.map |Int c -&gt; Str?| { return number % c == 0 ? digitsToStrings[c] : "" }.join;\n  }\n\n  private Str asTextFromDigit(Int number)\n  {\n    list := number.toStr.chars.map (|Int c -&gt; Obj?| { return digitsToStrings[c.fromDigit] } );\n    return list.join("") |Obj? c -&gt; Str| { c == null ? "": c };\n  }\n}\n</pre>\n        \n    </div>\n    \n    <div class="gist-meta">\n        \n        <span><a href="https://github.com/elefevre/FooBarQix/blob/master/FooBarQixFantom/fan/FooBarQix.fan">This Gist</a> brought to you by <a href="http://gist-it.appspot.com">gist-it</a>.</span>\n        \n        <span style="float: right; color: #369;"><a href="https://github.com/elefevre/FooBarQix/raw/master/FooBarQixFantom/fan/FooBarQix.fan">view raw</a></span>\n        <span style="float: right; margin-right: 8px;">\n            <a style="color: rgb(102, 102, 102);" href="https://github.com/elefevre/FooBarQix/blob/master/FooBarQixFantom/fan/FooBarQix.fan">FooBarQix.fan</a></span>\n            <!-- Generated by: http://gist-it.appspot.com -->\n    </div>\n    \n</div>\n</div>' );

document.write( '<script type="text/javascript">prettyPrint();</script>' );