if ( 'prettyPrint' in window ) {} else {
    document.write( '<script type="text/javascript" src="http://gist-it.appspot.com/assets/prettify/prettify.js"></script>' );
}


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/embed.css"/>' );


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/prettify/prettify.css"/>' );

document.write( '<div class="gist-it-gist">\n<div class="gist-file">\n    <div class="gist-data">\n        \n        <pre class="prettyprint">(1..100).each {\n    def pfx= it%3==0?\'Foo\':\'\'\n    pfx += it%5==0?\'Bar\':\'\'\n    pfx += it%7==0?\'Qix\':\'\'\n    \n    res = pfx + "$it".collect { n -&gt;       \n       (n==\'3\'?\'Foo\':n==\'5\'?\'Bar\':n==\'7\'?\'Qix\':pfx?\'\':n)\n    }.sum()\n\n    if (res =~ /[FBQ]/) res = res.replaceAll(/[0-9]/,\'\')\n    println "$it: $res"\n}\n</pre>\n        \n    </div>\n    \n    <div class="gist-meta">\n        \n        <span><a href="https://github.com/melix/CodeStory/blob/master/FooBarQix/FooBarQix.groovy">This Gist</a> brought to you by <a href="http://gist-it.appspot.com">gist-it</a>.</span>\n        \n        <span style="float: right; color: #369;"><a href="https://github.com/melix/CodeStory/raw/master/FooBarQix/FooBarQix.groovy">view raw</a></span>\n        <span style="float: right; margin-right: 8px;">\n            <a style="color: rgb(102, 102, 102);" href="https://github.com/melix/CodeStory/blob/master/FooBarQix/FooBarQix.groovy">FooBarQix.groovy</a></span>\n            <!-- Generated by: http://gist-it.appspot.com -->\n    </div>\n    \n</div>\n</div>' );

document.write( '<script type="text/javascript">prettyPrint();</script>' );