if ( 'prettyPrint' in window ) {} else {
    document.write( '<script type="text/javascript" src="http://gist-it.appspot.com/assets/prettify/prettify.js"></script>' );
}


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/embed.css"/>' );


document.write( '<link rel="stylesheet" href="http://gist-it.appspot.com/assets/prettify/prettify.css"/>' );

document.write( '<div class="gist-it-gist">\n<div class="gist-file">\n    <div class="gist-data">\n        \n        <pre class="prettyprint">class Main {\n  static Void main(Str[] args) {\n    echo(FBQNumber.count(100))\n  } \n}\n\nclass FBQNumber {\n  Int number\n  new make(Int number){\n    this.number = number\n  }\n  \n  static Str count(Int target) {\n    return (1..target).map |number-&gt;Str| { FBQNumber(number).toStr  } .join("\\n")\n  }\n\n  override Str toStr() {\n    Str result := ""\n    if (isMultiple(3)) result += "Foo"\n    if (isMultiple(5)) result +=  "Bar"\n    if (isMultiple(7)) result += "Qix"\n    \n    number.toStr().each |digit| { \n      if (digit.toChar=="3") result += "Foo" \n      if (digit.toChar=="5") result += "Bar" \n      if (digit.toChar=="7") result += "Qix" \n    }\n    \n    if (result == "") result += number.toStr \n    return result\n  }\n  \n  Bool isMultiple(Int multiple) {\n    return number !=0 &amp;&amp; number.mod(multiple)==0\n  }\n}</pre>\n        \n    </div>\n    \n    <div class="gist-meta">\n        \n        <span><a href="https://github.com/gtardif/FooBarQix-fantom/blob/master/src/FooBarQix.fan">This Gist</a> brought to you by <a href="http://gist-it.appspot.com">gist-it</a>.</span>\n        \n        <span style="float: right; color: #369;"><a href="https://github.com/gtardif/FooBarQix-fantom/raw/master/src/FooBarQix.fan">view raw</a></span>\n        <span style="float: right; margin-right: 8px;">\n            <a style="color: rgb(102, 102, 102);" href="https://github.com/gtardif/FooBarQix-fantom/blob/master/src/FooBarQix.fan">FooBarQix.fan</a></span>\n            <!-- Generated by: http://gist-it.appspot.com -->\n    </div>\n    \n</div>\n</div>' );

document.write( '<script type="text/javascript">prettyPrint();</script>' );